# Generated by Django 5.2.17 on 2026-08-19 08:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Bölge adı')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kısa kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Bölge',
                'verbose_name_plural': 'Bölgeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Tedarikçi adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Ad')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('kind', models.CharField(choices=[('FIXED_TANK', 'Sabit tank'), ('MOBILE_TANKER', 'Mobil tanker')], max_length=20, verbose_name='Tür')),
                ('capacity_liters', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Kapasite (L)')),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Düşük stok eşiği (L)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_units', to='fuel.region', verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'Depolama birimi',
                'verbose_name_plural': 'Depolama birimleri',
                'ordering': ['region_id', 'kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Araç/makine adı')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Araç kodu/plaka')),
                ('meter_type', models.CharField(choices=[('KM', 'Kilometre'), ('HOUR', 'Çalışma saati'), ('NONE', 'Sayaç yok')], default='NONE', max_length=10, verbose_name='Sayaç türü')),
                ('organization', models.CharField(blank=True, max_length=160, verbose_name='Bağlı firma/taşeron')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fuel.region', verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'Araç/makine',
                'verbose_name_plural': 'Araçlar/makineler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FuelMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING_BALANCE', 'Başlangıç stoğu'), ('SUPPLIER_RECEIPT', 'Tedarikçiden giriş'), ('INTERNAL_TRANSFER', 'İç transfer'), ('VEHICLE_FUELING', 'Araca yakıt verme'), ('STOCK_ADJUSTMENT', 'Stok düzeltmesi')], max_length=24, verbose_name='Hareket türü')),
                ('occurred_at', models.DateTimeField(verbose_name='İşlem tarihi')),
                ('liters', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Miktar (L)')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='İrsaliye no')),
                ('external_scale_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Tedarikçi kantarı (kg)')),
                ('company_scale_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Kurum kantarı (kg)')),
                ('meter_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Kilometre/çalışma saati')),
                ('note', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt zamanı')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='İptal zamanı')),
                ('void_reason', models.TextField(blank=True, verbose_name='İptal gerekçesi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fuel_movements', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı oluşturan')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_fuel_movements', to=settings.AUTH_USER_MODEL, verbose_name='İptal eden')),
                ('destination_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='fuel.storageunit', verbose_name='Hedef tank/tanker')),
                ('source_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='fuel.storageunit', verbose_name='Kaynak tank/tanker')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_movements', to='fuel.supplier', verbose_name='Tedarikçi')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_movements', to='fuel.vehicle', verbose_name='Araç/makine')),
            ],
            options={
                'verbose_name': 'Yakıt hareketi',
                'verbose_name_plural': 'Yakıt hareketleri',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='storageunit',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_liters__isnull', True), ('capacity_liters__gt', 0), _connector='OR'), name='storage_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='storageunit',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='storage_low_threshold_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='fuelmovement',
            index=models.Index(fields=['occurred_at', 'movement_type'], name='fuel_fuelmo_occurre_19bb67_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelmovement',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='fuel_fuelmo_vehicle_3cefcd_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelmovement',
            index=models.Index(fields=['source_storage', 'occurred_at'], name='fuel_fuelmo_source__591f23_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelmovement',
            index=models.Index(fields=['destination_storage', 'occurred_at'], name='fuel_fuelmo_destina_90031c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(('liters__gt', 0)), name='movement_liters_positive'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(('external_scale_kg__isnull', True), ('external_scale_kg__gte', 0), _connector='OR'), name='movement_external_scale_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(('company_scale_kg__isnull', True), ('company_scale_kg__gte', 0), _connector='OR'), name='movement_company_scale_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(('meter_value__isnull', True), ('meter_value__gte', 0), _connector='OR'), name='movement_meter_nonnegative'),
        ),
    ]
