# Generated by Django 5.2.17 on 2026-08-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelmovement',
            name='corrects',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='fuel.fuelmovement', verbose_name='Düzeltilen hareket'),
        ),
    ]
