# Generated by Django 5.2.17 on 2026-08-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_movement_regions(apps, schema_editor):
    FuelMovement = apps.get_model("fuel", "FuelMovement")
    movements = FuelMovement.objects.select_related(
        "source_storage",
        "destination_storage",
    )
    for movement in movements.iterator():
        FuelMovement.objects.filter(pk=movement.pk).update(
            source_region_id=(
                movement.source_storage.region_id
                if movement.source_storage_id
                else None
            ),
            destination_region_id=(
                movement.destination_storage.region_id
                if movement.destination_storage_id
                else None
            ),
        )


def clear_movement_regions(apps, schema_editor):
    FuelMovement = apps.get_model("fuel", "FuelMovement")
    FuelMovement.objects.update(source_region_id=None, destination_region_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fuelmovement_corrects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageRegionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(verbose_name='Değişiklik tarihi')),
                ('reason', models.TextField(verbose_name='Değişiklik gerekçesi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt zamanı')),
            ],
            options={
                'verbose_name': 'Tank/tanker bölge değişikliği',
                'verbose_name_plural': 'Tank/tanker bölge değişiklikleri',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fuelmovement',
            name='destination_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_fuel_movements', to='fuel.region', verbose_name='Hedef işlem bölgesi'),
        ),
        migrations.AddField(
            model_name='fuelmovement',
            name='source_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_fuel_movements', to='fuel.region', verbose_name='Kaynak işlem bölgesi'),
        ),
        migrations.RunPython(backfill_movement_regions, clear_movement_regions),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_region__isnull', True), ('source_storage__isnull', True)), models.Q(('source_region__isnull', False), ('source_storage__isnull', False)), _connector='OR'), name='movement_source_region_matches_storage'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_region__isnull', True), ('destination_storage__isnull', True)), models.Q(('destination_region__isnull', False), ('destination_storage__isnull', False)), _connector='OR'), name='movement_destination_region_matches_storage'),
        ),
        migrations.AddField(
            model_name='storageregionchange',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_storage_region_changes', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı oluşturan'),
        ),
        migrations.AddField(
            model_name='storageregionchange',
            name='from_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_region_departures', to='fuel.region', verbose_name='Eski bölge'),
        ),
        migrations.AddField(
            model_name='storageregionchange',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='region_changes', to='fuel.storageunit', verbose_name='Tank/tanker'),
        ),
        migrations.AddField(
            model_name='storageregionchange',
            name='to_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_region_arrivals', to='fuel.region', verbose_name='Yeni bölge'),
        ),
        migrations.AddIndex(
            model_name='storageregionchange',
            index=models.Index(fields=['storage', 'occurred_at'], name='fuel_storag_storage_01045d_idx'),
        ),
        migrations.AddConstraint(
            model_name='storageregionchange',
            constraint=models.CheckConstraint(condition=models.Q(('from_region', models.F('to_region')), _negated=True), name='storage_region_change_regions_differ'),
        ),
    ]
