# Generated by Django 5.2.17 on 2026-08-20 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_vehicle_regions(apps, schema_editor):
    FuelMovement = apps.get_model("fuel", "FuelMovement")
    movements = FuelMovement.objects.select_related("vehicle")
    for movement in movements.iterator():
        FuelMovement.objects.filter(pk=movement.pk).update(
            vehicle_region_id=(
                movement.vehicle.region_id if movement.vehicle_id else None
            )
        )


def clear_vehicle_regions(apps, schema_editor):
    FuelMovement = apps.get_model("fuel", "FuelMovement")
    FuelMovement.objects.update(vehicle_region_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_storage_region_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(verbose_name='Değişiklik tarihi')),
                ('reason', models.TextField(verbose_name='Değişiklik gerekçesi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt zamanı')),
            ],
            options={
                'verbose_name': 'Araç/makine bölge değişikliği',
                'verbose_name_plural': 'Araç/makine bölge değişiklikleri',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fuelmovement',
            name='vehicle_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fuel_movements', to='fuel.region', verbose_name='Araç işlem bölgesi'),
        ),
        migrations.RunPython(backfill_vehicle_regions, clear_vehicle_regions),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('vehicle__isnull', True), ('vehicle_region__isnull', True)), models.Q(('vehicle__isnull', False), ('vehicle_region__isnull', False)), _connector='OR'), name='movement_vehicle_region_matches_vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleregionchange',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vehicle_region_changes', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı oluşturan'),
        ),
        migrations.AddField(
            model_name='vehicleregionchange',
            name='from_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_region_departures', to='fuel.region', verbose_name='Eski bölge'),
        ),
        migrations.AddField(
            model_name='vehicleregionchange',
            name='to_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_region_arrivals', to='fuel.region', verbose_name='Yeni bölge'),
        ),
        migrations.AddField(
            model_name='vehicleregionchange',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='region_changes', to='fuel.vehicle', verbose_name='Araç/makine'),
        ),
        migrations.AddIndex(
            model_name='vehicleregionchange',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='fuel_vehicl_vehicle_32103c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleregionchange',
            constraint=models.CheckConstraint(condition=models.Q(('from_region', models.F('to_region')), _negated=True), name='vehicle_region_change_regions_differ'),
        ),
    ]
