# Generated by Django 5.2.17 on 2026-08-21 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_vehicle_tag_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(verbose_name='Yakıt verme tarihi')),
                ('liters', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Miktar (L)')),
                ('meter_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Kilometre/çalışma saati')),
                ('note', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('PENDING', 'Onay bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=12, verbose_name='Durum')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim zamanı')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Karar zamanı')),
                ('decision_reason', models.TextField(blank=True, verbose_name='Karar açıklaması')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_fueling_requests', to=settings.AUTH_USER_MODEL, verbose_name='Karar veren')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_request', to='fuel.fuelmovement', verbose_name='Oluşan yakıt hareketi')),
                ('source_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_fueling_requests', to='fuel.region', verbose_name='Kaynak işlem bölgesi')),
                ('source_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fueling_requests', to='fuel.storageunit', verbose_name='Yakıtı veren tank/tanker')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_fueling_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen operatör')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fueling_requests', to='fuel.vehicle', verbose_name='Araç/makine')),
                ('vehicle_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fueling_requests', to='fuel.region', verbose_name='Araç işlem bölgesi')),
            ],
            options={
                'verbose_name': 'Saha yakıt kaydı',
                'verbose_name_plural': 'Saha yakıt kayıtları',
                'ordering': ['-submitted_at', '-id'],
                'permissions': [('approve_fuelingrequest', 'Saha yakıt kayıtlarını onaylayabilir')],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='fuel_fuelin_status_eb067a_idx'), models.Index(fields=['submitted_by', 'status'], name='fuel_fuelin_submitt_c42c52_idx'), models.Index(fields=['source_region', 'status'], name='fuel_fuelin_source__1a5c4d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('liters__gt', 0)), name='fueling_request_liters_positive'), models.CheckConstraint(condition=models.Q(('meter_value__isnull', True), ('meter_value__gte', 0), _connector='OR'), name='fueling_request_meter_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='OperatorStorageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_accesses', to='fuel.storageunit', verbose_name='Yetkili tank/tanker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_storage_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Saha operatörü')),
            ],
            options={
                'verbose_name': 'Operatör tank/tanker yetkisi',
                'verbose_name_plural': 'Operatör tank/tanker yetkileri',
                'ordering': ['user__username', 'storage__region__name', 'storage__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'storage'), name='operator_storage_access_unique')],
            },
        ),
    ]
