# Generated by Django 5.2.17 on 2026-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_movement_source_differs_from_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='meter_type',
            field=models.CharField(choices=[('KM', 'Kilometre'), ('HOUR', 'Çalışma saati'), ('TASERON', 'Taşeron'), ('NONE', 'Sayaç yok')], default='NONE', max_length=10, verbose_name='Sayaç türü'),
        ),
    ]
