# Generated by Django 5.2.17 on 2026-08-24 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0009_vehicle_contractor_classification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorFuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField(db_index=True, verbose_name='Geçerlilik başlangıcı')),
                ('reference_unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Referans ortalama fiyat (TL/L)')),
                ('contractor_unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Taşerona yansıtılacak fiyat (TL/L)')),
                ('note', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt zamanı')),
            ],
            options={
                'verbose_name': 'Taşeron yakıt fiyatı',
                'verbose_name_plural': 'Taşeron yakıt fiyatları',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fuelingrequest',
            name='contractor_reference_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Taşeron referans ortalama fiyatı (TL/L)'),
        ),
        migrations.AddField(
            model_name='fuelingrequest',
            name='contractor_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Taşerona yansıtılacak fiyat (TL/L)'),
        ),
        migrations.AddField(
            model_name='fuelmovement',
            name='contractor_reference_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Taşeron referans ortalama fiyatı (TL/L)'),
        ),
        migrations.AddField(
            model_name='fuelmovement',
            name='contractor_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Taşerona yansıtılan fiyat (TL/L)'),
        ),
        migrations.AddField(
            model_name='fuelmovement',
            name='purchase_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Alış birim fiyatı (TL/L)'),
        ),
        migrations.AddConstraint(
            model_name='fuelingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('contractor_reference_unit_price__isnull', True), ('contractor_reference_unit_price__gt', 0), _connector='OR'), name='fueling_request_reference_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='fuelingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('contractor_unit_price__isnull', True), ('contractor_unit_price__gt', 0), _connector='OR'), name='fueling_request_contractor_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_unit_price__isnull', True), ('purchase_unit_price__gt', 0), _connector='OR'), name='movement_purchase_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(('contractor_reference_unit_price__isnull', True), ('contractor_reference_unit_price__gt', 0), _connector='OR'), name='movement_contractor_reference_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='fuelmovement',
            constraint=models.CheckConstraint(condition=models.Q(('contractor_unit_price__isnull', True), ('contractor_unit_price__gt', 0), _connector='OR'), name='movement_contractor_price_positive'),
        ),
        migrations.AddField(
            model_name='contractorfuelprice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contractor_fuel_prices', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı oluşturan'),
        ),
        migrations.AddConstraint(
            model_name='contractorfuelprice',
            constraint=models.CheckConstraint(condition=models.Q(('reference_unit_price__gt', 0)), name='contractor_price_reference_positive'),
        ),
        migrations.AddConstraint(
            model_name='contractorfuelprice',
            constraint=models.CheckConstraint(condition=models.Q(('contractor_unit_price__gt', 0)), name='contractor_price_charge_positive'),
        ),
    ]
